bridges = []
persistence_dir = '.'
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'development-agent'
keystore_file = 'unused'
name = 'acorn user'
public_address = 'HcScIc8G7X769Nr6cnRxgR73wi8au946z7hc46EMDJjaz8au4bD7V6hj7T6B8fa'
test_agent = true

[[dnas]]
file = './dnas/profiles/dist/profiles.dna.json'
hash = 'QmdGgs8UFtqyV9ed7offX4znEEdZJ3QXEfUjCjBQ44Dbyv'
id = 'profiles-dna'

[[instances]]
agent = 'development-agent'
dna = 'profiles-dna'
id = 'profiles-instance'

[instances.storage]
type = 'memory'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = 'profiles-instance'

[interfaces.driver]
port = 8888
type = 'websocket'

[logger]
state_dump = false
type = 'info'

[logger.rules]
rules = []

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
