[package]
name = "acorn_projects"
version = "0.4.0"
edition = "2018"

[dependencies]
serde = "=1.0.104"
# patched
hdk3 = "0"
derive_more = "0.99.9"
dna_help = { path = "../../../../crates/dna_help" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
