image: rust:1.23

stages:
  - build
  - test

build-lib:
  stage: build
  script:
    - cargo build --lib --features strict

build-examples:
  stage: build
  script:
    - cargo build --examples

test:
  stage: test
  script:
    # with default feature std
    - cargo test

    # without default feature std
    # donâ€™t try to build examples (rust-lang/cargo#5387)
    - cargo test --no-default-features --lib --tests
